---
title: "Example document recreated with `beamer` in \\LaTeX"
author: "Your Name"
date: |
      |
      |
      |
      |
      |
      | 
      | Fall 2019
output: 
 beamer_presentation:
   latex_engine: xelatex
   theme: "default"
   colortheme: "beaver"
---

# Outline

Working with equations

|     Aligning the same equations
|     Omit equation numbering
|     Ugly alignment 

Discussion

# Working with equations

We define a set of equations as:

\begin{equation} 
a = b + c^2,
\end{equation} 

\begin{equation} 
a - c^2 = b,
\end{equation} 

\begin{equation} 
\text{left side} = \text{right side},
\end{equation} 

\begin{equation} 
\text{left side} + \text{something}  \geq \text{right side},
\end{equation} 

for all something >0

# Aligning the same equations

Aligning the equations by the equal sign gives a much better view into the placements
of the separate equation components:

\begin{align} 
a &= b + c^2,\\
a - c^2 &= b,\\
\text{left side} &= \text{right side},\\
\text{left side} + \text{something} & \geq \text{right side},
\end{align}   

for all something >0

# Omit equation numbering

Alternatively, the equation numbering can be omitted:

\begin{align*} 
a &= b + c^2,\\
a - c^2 &= b,\\
\text{left side} &= \text{right side},\\
\text{left side} + \text{something} & \geq \text{right side},
\end{align*}   

# Ugly alignment

Some components do not look well, when aligned. Especially equations with different
heights and spacing. For example:

\begin{align} 
 E &= mc^2,\\
 m &= \frac{E}{c^2},\\
 c &= \sqrt{\frac{E}{m}},
\end{align}   

Take that into account

# Discussion

This is where you’d normally give your audience a recap of your talk, where you could
discuss e.g. the following:

 - Your main findings
 - The consequences of your main findings
 - Things to do
 - Any other business not curr
